import Head from 'next/head'
import Main from '../Layout/Main/Main'
import Header from '../Layout/Header/Header'
import Footer from '../Layout/Footer/Footer'


export default function Home() {
  return (
    <>
    <Head>
        <title>Trip Your Picks</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Header />
    <Main />
    <Footer />
    </>
  )
}