import Head from 'next/head'
import Main from '../Layout/Main/Main'
import Header from '../Layout/Header/Header'


export default function Home() {
  return (
    <>
    <Head>
        <title>Trip Your Picks</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        {/* <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=f6030893c8db256b0171d97340aeda47"></script> */}
    </Head>
    <Header />
    <Main />
    </>
  )
}